#!/bin/bash

# DASHBOARD DEPLOYMENT SCRIPT
# Generated by: Claude Code
# Date: 2025-11-14
# Purpose: Deploy Dashboard droplet #2 to production server
#
# SECURITY: Review this script before running
# This script should be executed ON THE SERVER (198.54.123.234)
#
# Usage:
#   1. Copy this script to the server
#   2. Review the script carefully
#   3. Run: bash DEPLOY_TO_SERVER_MANUAL.sh

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 DASHBOARD DEPLOYMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Configuration
REPO_URL="https://github.com/jamessunheart/dashboard.git"
APP_NAME="dashboard"
DEPLOY_PATH="/opt/fpai/apps/${APP_NAME}"
SERVICE_PORT=8002
PYTHON_VERSION="python3.11"  # Server likely has 3.11, not 3.13

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

print_step() { echo -e "${BLUE}[$1/8]${NC} $2"; }
print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_error() { echo -e "${RED}❌ $1${NC}"; }
print_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }

# Step 1: Create deployment directory
print_step 1 "Creating deployment directory..."
mkdir -p /opt/fpai/apps
cd /opt/fpai/apps

if [ -d "$APP_NAME" ]; then
    print_info "Dashboard directory exists, backing up..."
    BACKUP_NAME="${APP_NAME}-backup-$(date +%Y%m%d-%H%M%S)"
    cp -r "$APP_NAME" "$BACKUP_NAME"
    print_success "Backup created: $BACKUP_NAME"
else
    print_info "First-time deployment"
fi

# Step 2: Clone or pull repository
print_step 2 "Getting latest code from GitHub..."
if [ -d "$APP_NAME/.git" ]; then
    cd "$APP_NAME"
    git fetch origin
    git pull origin main
    print_success "Code updated from GitHub"
else
    git clone "$REPO_URL" "$APP_NAME"
    cd "$APP_NAME"
    print_success "Repository cloned"
fi

# Step 3: Set up Python virtual environment
print_step 3 "Setting up Python environment..."
if [ ! -d ".venv" ]; then
    $PYTHON_VERSION -m venv .venv
    print_success "Virtual environment created"
else
    print_info "Virtual environment exists"
fi

# Step 4: Install dependencies
print_step 4 "Installing dependencies..."
source .venv/bin/activate
pip install --upgrade pip -q
pip install -r requirements.txt -q
pip install pytest -q  # For testing
print_success "Dependencies installed"

# Step 5: Run tests
print_step 5 "Running tests..."
if pytest -v; then
    print_success "All tests passed"
else
    print_error "Tests failed - aborting deployment"
    exit 1
fi

# Step 6: Create systemd service
print_step 6 "Creating systemd service..."
cat > "/etc/systemd/system/fpai-${APP_NAME}.service" <<EOF
[Unit]
Description=Full Potential AI - Dashboard
After=network.target
Wants=fpai-registry.service fpai-orchestrator.service

[Service]
Type=simple
User=root
WorkingDirectory=${DEPLOY_PATH}
Environment="PATH=${DEPLOY_PATH}/.venv/bin:/usr/local/bin:/usr/bin:/bin"
Environment="REGISTRY_URL=http://localhost:8000"
Environment="ORCHESTRATOR_URL=http://localhost:8001"
Environment="PORT=${SERVICE_PORT}"
ExecStart=${DEPLOY_PATH}/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port ${SERVICE_PORT}
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

print_success "Systemd service created"

# Step 7: Enable and start service
print_step 7 "Starting service..."
systemctl daemon-reload
systemctl enable fpai-${APP_NAME}
systemctl restart fpai-${APP_NAME}
print_success "Service started"

# Wait for service to initialize
print_info "Waiting for service to initialize..."
sleep 5

# Step 8: Health check
print_step 8 "Verifying deployment..."
HEALTH_URL="http://localhost:${SERVICE_PORT}/health"

MAX_RETRIES=10
RETRY_COUNT=0

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if curl -f -s "$HEALTH_URL" > /dev/null 2>&1; then
        print_success "Health check passed!"
        echo ""
        print_info "Health response:"
        curl -s "$HEALTH_URL" | python3 -m json.tool
        break
    fi

    RETRY_COUNT=$((RETRY_COUNT + 1))
    if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
        echo "   Attempt $RETRY_COUNT/$MAX_RETRIES - retrying..."
        sleep 3
    fi
done

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    print_error "Health check failed"
    print_info "Checking service logs..."
    journalctl -u fpai-${APP_NAME} -n 30 --no-pager
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
print_success "DEPLOYMENT COMPLETE!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
print_info "Service: fpai-${APP_NAME}"
print_info "Port: ${SERVICE_PORT}"
print_info "Health: http://localhost:${SERVICE_PORT}/health"
print_info "Public: http://198.54.123.234:${SERVICE_PORT}"
echo ""
print_info "View logs: journalctl -u fpai-${APP_NAME} -f"
print_info "Check status: systemctl status fpai-${APP_NAME}"
print_info "Restart: systemctl restart fpai-${APP_NAME}"
echo ""
echo "🌐⚡💎"
